source 'https://rubygems.org'


gem 'rails', '4.0.4'
gem 'pg'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'active_model_serializers'
gem 'handlebars_assets'
gem 'rack-cors', :require => 'rack/cors'


group :test, :development do
  gem 'rspec-rails'
  gem 'pry'
  gem 'shoulda-matchers'
  gem 'better_errors'
  gem 'capybara'
  gem 'launchy'
  gem 'faker'
  gem 'factory_girl_rails'
end

group :test do
  gem 'database_cleaner'
end

